[project]
name = "sica-mapping"
version = "0.1.0"
authors = [
    { name = "bubblbu", email = "asura.enkhbayar@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "pandas",
    "folium",
    "shapely",
    "loguru",
    "polars>=1.44.2",
    "geopandas>=1.1.4",
    "pyogrio>=0.13.0",
    "tomlkit>=0.15.1",
    "requests>=2.32.5",
]

[build-system]
requires = ["uv_build>=0.9.3,<0.10.0"]
build-backend = "uv_build"
